### ISSUE TITLE
Quickstart step 4 fails

### ISSUE THREAD

**Issue by hh-vincit** [NVIDIA-ISAAC-ROS/ros2_benchmark#12]
The instructions contain a git cherry-pick command that doesn't work.
```
root@6691e93ed425:~/ros_ws/src/image_pipeline# git cherry-pick fork/pr-backport-693
error: commit 03d1da848f62cb80ad7239fb63ccc5620225ac3e is a merge but no -m option was given.
fatal: cherry-pick failed
```

**Comment by hemalshahNV** [comment]
The [patch](https://github.com/ros-perception/image_pipeline/pull/786) for image_pipeline needed to fix publishing resized images to the same topic it received them on was recently merged with a different PR into the `humble` branch of the `ros-perception` repository. We're updating the instructions now, but you can work around this by removing the line `git remote add fork https://github.com/schornakj/image_pipeline.git && git fetch fork && git cherry-pick fork/pr-backport-693 && \` from Step 4. When the change has been included in the binary builds of ROS 2 Humble, we will remove Step 4 entirely.
