### ISSUE TITLE
colcon test --packages-select ros2_benchmark | fails 

### ISSUE THREAD

**Issue by OsamaThakur** [NVIDIA-ISAAC-ROS/ros2_benchmark#16]
Running Step 7 in quickstart guide I run into the following error

```
$ colcon test --packages-select ros2_benchmark 
Starting >>> ros2_benchmark
[Processing: ros2_benchmark]                   
--- stderr: ros2_benchmark                     
Errors while running CTest
Output from these tests are in: /root/ros_ws/build/ros2_benchmark/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
---
Finished <<< ros2_benchmark [34.9s]	[ with test failures ]

Summary: 1 package finished [35.0s]
  1 package had stderr output: ros2_benchmark
  1 package had test failures: ros2_benchmark
```
Opening the output file
```
$ cat /root/ros_ws/build/ros2_benchmark/Testing/Temporary/LastTest.log
Start testing: Sep 12 11:22 UTC
----------------------------------------------------------
End testing: Sep 12 11:22 UTC
```

**Comment by swapnesh-wani-nvidia** [comment]
Hello, could you share the full log for the test failure? You could also print out the log spew in-line with this flag `--event-handlers console_direct+` for e.g `colcon test --packages-select ros2_benchmark  --event-handlers console_direct+`

**Comment by OsamaThakur** [comment]
"""
Starting >>> ros2_benchmark
UpdateCTestConfiguration  from :/root/ros_ws/build/ros2_benchmark/CTestConfiguration.ini
Parse Config file:/root/ros_ws/build/ros2_benchmark/CTestConfiguration.ini
   Site: osthakur
   Build name: (empty)
 Add coverage exclude regular expressions.
Create new tag: 20230920-0937 - Experimental
UpdateCTestConfiguration  from :/root/ros_ws/build/ros2_benchmark/CTestConfiguration.ini
Parse Config file:/root/ros_ws/build/ros2_benchmark/CTestConfiguration.ini
Test project /root/ros_ws/build/ros2_benchmark
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: test_data_loader_node_pol.py

1: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_data_loader_node_pol.py.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/launch_test/test_data_loader_node_pol.py.txt" "--command" "/usr/bin/python3" "-m" "launch_testing.launch_test" "/root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/data_loader_node_pol.py" "--junit-xml=/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_data_loader_node_pol.py.xunit.xml" "--package-name=ros2_benchmark"
1: Test timeout computed to be: 15
1: -- run_test.py: invoking following command in '/root/ros_ws/build/ros2_benchmark':
1:  - /usr/bin/python3 -m launch_testing.launch_test /root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/data_loader_node_pol.py --junit-xml=/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_data_loader_node_pol.py.xunit.xml --package-name=ros2_benchmark
1: [INFO] [launch]: All log files can be found below /root/.ros/log/2023-09-20-09-37-13-787189-osthakur-8963
1: [INFO] [launch]: Default logging verbosity is set to INFO
1: test_data_loader_node_services (ros2_benchmark.TestDataLoaderNode)
1: Test services hosted in DataLoaderNode. ... [INFO] [component_container_mt-1]: process started with pid [8983]
1: [component_container_mt-1] [INFO] [1695202634.063447576] [data_loader_container]: Load Library: /root/ros_ws/install/ros2_benchmark/lib/libdata_loader_node.so
1: [component_container_mt-1] [INFO] [1695202634.064667471] [data_loader_container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::DataLoaderNode>
1: [component_container_mt-1] [INFO] [1695202634.064686543] [data_loader_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::DataLoaderNode>
1: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/DataLoaderNode' in container '/data_loader_container'
1: [component_container_mt-1] [INFO] [1695202634.076321830] [DataLoaderNode]: Set the rosbag file to be: /root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/pol.bag/pol.bag_0.db3
1: [component_container_mt-1] [ERROR] [1695202634.076880890] [rosbag2_storage]: Could not open '/root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/pol.bag/pol.bag_0.db3' with 'sqlite3'. Error: Failed to setup storage. Error: Error when processing SQL statement. SQLite error (26): file is not a database
1: [component_container_mt-1] [ERROR] [1695202634.076891595] [rosbag2_storage]: Could not load/open plugin with storage id 'sqlite3'
1: [component_container_mt-1] [ERROR] [1695202634.076904687] [DataLoaderNode]: Failed to open the rosbag: No storage could be initialized from the inputs.
1: FAIL
1: 
1: ======================================================================
1: FAIL: test_data_loader_node_services (ros2_benchmark.TestDataLoaderNode)
1: Test services hosted in DataLoaderNode.
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "/root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/data_loader_node_pol.py", line 95, in test_data_loader_node_services
1:     self.assertTrue(set_data_response.success)
1: AssertionError: False is not true
1: 
1: ----------------------------------------------------------------------
1: Ran 1 test in 0.265s
1: 
1: FAILED (failures=1)
1: [INFO] [component_container_mt-1]: sending signal 'SIGINT' to process[component_container_mt-1]
1: [component_container_mt-1] [INFO] [1695202635.071942182] [rclcpp]: signal_handler(signum=2)
1: [INFO] [component_container_mt-1]: process has finished cleanly [pid 8983]
1: 
1: ----------------------------------------------------------------------
1: Ran 0 tests in 0.000s
1: 
1: OK
1: -- run_test.py: return code 1             
1: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_data_loader_node_pol.py.xunit.xml'
 1/11 Test  #1: test_data_loader_node_pol.py .....***Failed    1.72 sec
test 2
      Start  2: test_monitor_node_pol.py

2: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_monitor_node_pol.py.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/launch_test/test_monitor_node_pol.py.txt" "--command" "/usr/bin/python3" "-m" "launch_testing.launch_test" "/root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/monitor_node_pol.py" "--junit-xml=/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_monitor_node_pol.py.xunit.xml" "--package-name=ros2_benchmark"
2: Test timeout computed to be: 15
2: -- run_test.py: invoking following command in '/root/ros_ws/build/ros2_benchmark':
2:  - /usr/bin/python3 -m launch_testing.launch_test /root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/monitor_node_pol.py --junit-xml=/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_monitor_node_pol.py.xunit.xml --package-name=ros2_benchmark
2: [INFO] [launch]: All log files can be found below /root/.ros/log/2023-09-20-09-37-15-499076-osthakur-9010
2: [INFO] [launch]: Default logging verbosity is set to INFO
2: test_monitor_node_services (ros2_benchmark.TestMonitorNode)
2: Test services hosted in MonitorNode. ... [INFO] [ros2-1]: process started with pid [9030]
2: [INFO] [component_container_mt-2]: process started with pid [9032]
2: [ros2-1] Exception on parsing info file: yaml-cpp: error at line 1, column 1: operator[] call on a scalar (key: "rosbag2_bagfile_information")
2: [ERROR] [ros2-1]: process has died [pid 9030, exit code 1, cmd 'ros2 bag play /root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/pol.bag'].
2: [component_container_mt-2] [INFO] [1695202635.775646773] [monitor_container]: Load Library: /root/ros_ws/install/ros2_benchmark/lib/libmonitor_node.so
2: [component_container_mt-2] [INFO] [1695202635.776004219] [monitor_container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::MonitorNode>
2: [component_container_mt-2] [INFO] [1695202635.776015037] [monitor_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::MonitorNode>
2: [component_container_mt-2] [INFO] [1695202635.778286909] [MonitorNode0]: [MonitorNode] Starting a monitor node with a service name "start_monitoring0"
2: [component_container_mt-2] [INFO] [1695202635.779157735] [MonitorNode0]: [MonitorNode] Created a generic type monitor subscriber: topic="/image"
2: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/MonitorNode0' in container '/monitor_container'
2: [component_container_mt-2] [INFO] [1695202635.780149199] [monitor_container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::MonitorNode>
2: [component_container_mt-2] [INFO] [1695202635.780166191] [monitor_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::MonitorNode>
2: [component_container_mt-2] [INFO] [1695202635.781923480] [MonitorNode1]: [MonitorNode] Starting a monitor node with a service name "start_monitoring1"
2: [component_container_mt-2] [INFO] [1695202635.782208748] [MonitorNode1]: [MonitorNode] Created a generic type monitor subscriber: topic="/camera_info"
2: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/MonitorNode1' in container '/monitor_container'
 2/11 Test  #2: test_monitor_node_pol.py .........***Timeout  15.01 sec
test 3
      Start  3: test_playback_node_pol.py

3: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_playback_node_pol.py.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/launch_test/test_playback_node_pol.py.txt" "--command" "/usr/bin/python3" "-m" "launch_testing.launch_test" "/root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/playback_node_pol.py" "--junit-xml=/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_playback_node_pol.py.xunit.xml" "--package-name=ros2_benchmark"
3: Test timeout computed to be: 15
3: -- run_test.py: invoking following command in '/root/ros_ws/build/ros2_benchmark':
3:  - /usr/bin/python3 -m launch_testing.launch_test /root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/playback_node_pol.py --junit-xml=/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/test_playback_node_pol.py.xunit.xml --package-name=ros2_benchmark
3: [INFO] [launch]: All log files can be found below /root/.ros/log/2023-09-20-09-37-30-512930-osthakur-9061
3: [INFO] [launch]: Default logging verbosity is set to INFO
3: test_playback_node_services (ros2_benchmark.TestPlaybackNode)
3: Test services hosted in PlaybackNode. ... [INFO] [ros2-1]: process started with pid [9081]
3: [INFO] [component_container_mt-2]: process started with pid [9083]
3: [ros2-1] Exception on parsing info file: yaml-cpp: error at line 1, column 1: operator[] call on a scalar (key: "rosbag2_bagfile_information")
3: [ERROR] [ros2-1]: process has died [pid 9081, exit code 1, cmd 'ros2 bag play /root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/pol.bag --remap image:=/buffer/image'].
3: [component_container_mt-2] [INFO] [1695202650.788858038] [playback_container]: Load Library: /root/ros_ws/install/ros2_benchmark/lib/libplayback_node.so
3: [component_container_mt-2] [INFO] [1695202650.789329245] [playback_container]: Found class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::PlaybackNode>
3: [component_container_mt-2] [INFO] [1695202650.789339090] [playback_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<ros2_benchmark::PlaybackNode>
3: [component_container_mt-2] [INFO] [1695202650.792633589] [PlaybackNode]: Created a generic publisher: topic="/image"
3: [component_container_mt-2] [INFO] [1695202650.792818876] [PlaybackNode]: Created a generic subscriber: topic="/buffer/image"
3: [INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/PlaybackNode' in container '/playback_container'
3: [component_container_mt-2] [INFO] [1695202650.802452688] [PlaybackNode]: start_recording service began
[Processing: ros2_benchmark]                   
 3/11 Test  #3: test_playback_node_pol.py ........***Timeout  15.02 sec
test 4
      Start  4: copyright

4: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/copyright.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_copyright/copyright.txt" "--command" "/opt/ros/humble/bin/ament_copyright" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/copyright.xunit.xml"
4: Test timeout computed to be: 200
4: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
4:  - /opt/ros/humble/bin/ament_copyright --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/copyright.xunit.xml
4: No problems found, checked 20 files         
4: -- run_test.py: return code 0
4: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/copyright.xunit.xml'
 4/11 Test  #4: copyright ........................   Passed    0.29 sec
test 5
      Start  5: cppcheck

5: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cppcheck.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_cppcheck/cppcheck.txt" "--command" "/opt/ros/humble/bin/ament_cppcheck" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cppcheck.xunit.xml" "--include_dirs" "/root/ros_ws/src/ros2_benchmark/ros2_benchmark/include"
5: Test timeout computed to be: 300
5: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
5:  - /opt/ros/humble/bin/ament_cppcheck --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cppcheck.xunit.xml --include_dirs /root/ros_ws/src/ros2_benchmark/ros2_benchmark/include
5: cppcheck 2.7 has known performance issues and therefore will not be used, set the AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS environment variable to override this.
5: -- run_test.py: return code 0
5: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cppcheck.xunit.xml'
 5/11 Test  #5: cppcheck .........................   Passed    0.09 sec
test 6
      Start  6: cpplint

6: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cpplint.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_cpplint/cpplint.txt" "--command" "/opt/ros/humble/bin/ament_cpplint" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cpplint.xunit.xml"
6: Test timeout computed to be: 120
6: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
6:  - /opt/ros/humble/bin/ament_cpplint --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cpplint.xunit.xml
6: Using '--root=/root/ros_ws/src/ros2_benchmark/ros2_benchmark/include' argument
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/include/ros2_benchmark/common.hpp
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/include/ros2_benchmark/data_loader_node.hpp
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/include/ros2_benchmark/monitor_node.hpp
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/include/ros2_benchmark/playback_node.hpp
6: 
6: Using '--root=/root/ros_ws/src/ros2_benchmark/ros2_benchmark/src' argument
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/src/data_loader_node.cpp
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/src/monitor_node.cpp
6: 
6: Done processing /root/ros_ws/src/ros2_benchmark/ros2_benchmark/src/playback_node.cpp
6: 
6: No problems found
6: -- run_test.py: return code 0
6: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/cpplint.xunit.xml'
 6/11 Test  #6: cpplint ..........................   Passed    0.30 sec
test 7
      Start  7: flake8

7: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/flake8.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_flake8/flake8.txt" "--command" "/opt/ros/humble/bin/ament_flake8" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/flake8.xunit.xml"
7: Test timeout computed to be: 60
7: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
7:  - /opt/ros/humble/bin/ament_flake8 --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/flake8.xunit.xml
7:                                             
7: 13 files checked
7: No problems found
7: 
7: Checked files:
7: 
7: * ./ros2_benchmark/basic_performance_calculator.py
7: * ./ros2_benchmark/ros2_benchmark_test.py
7: * ./ros2_benchmark/ros2_benchmark_config.py
7: * ./ros2_benchmark/__init__.py
7: * ./ros2_benchmark/utils/image_utility.py
7: * ./ros2_benchmark/utils/nsys_utility.py
7: * ./ros2_benchmark/utils/cpu_profiler.py
7: * ./ros2_benchmark/utils/profiler.py
7: * ./ros2_benchmark/utils/ros2_utility.py
7: * ./ros2_benchmark/utils/__init__.py
7: * ./test/playback_node_pol.py
7: * ./test/monitor_node_pol.py
7: * ./test/data_loader_node_pol.py
7: -- run_test.py: return code 0
7: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/flake8.xunit.xml'
 7/11 Test  #7: flake8 ...........................   Passed    0.26 sec
test 8
      Start  8: lint_cmake

8: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/lint_cmake.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_lint_cmake/lint_cmake.txt" "--command" "/opt/ros/humble/bin/ament_lint_cmake" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/lint_cmake.xunit.xml"
8: Test timeout computed to be: 60
8: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
8:  - /opt/ros/humble/bin/ament_lint_cmake --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/lint_cmake.xunit.xml
8: 
8: No problems found
8: -- run_test.py: return code 0               
8: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/lint_cmake.xunit.xml'
 8/11 Test  #8: lint_cmake .......................   Passed    0.08 sec
test 9
      Start  9: pep257

9: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/pep257.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_pep257/pep257.txt" "--command" "/opt/ros/humble/bin/ament_pep257" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/pep257.xunit.xml"
9: Test timeout computed to be: 60
9: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
9:  - /opt/ros/humble/bin/ament_pep257 --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/pep257.xunit.xml
9: checking ./ros2_benchmark/__init__.py       
9: checking ./ros2_benchmark/basic_performance_calculator.py
9: checking ./ros2_benchmark/ros2_benchmark_config.py
9: checking ./ros2_benchmark/ros2_benchmark_test.py
9: checking ./ros2_benchmark/utils/__init__.py
9: checking ./ros2_benchmark/utils/cpu_profiler.py
9: checking ./ros2_benchmark/utils/image_utility.py
9: checking ./ros2_benchmark/utils/nsys_utility.py
9: checking ./ros2_benchmark/utils/profiler.py
9: checking ./ros2_benchmark/utils/ros2_utility.py
9: checking ./test/data_loader_node_pol.py
9: checking ./test/monitor_node_pol.py
9: checking ./test/playback_node_pol.py
9: No problems found
9: -- run_test.py: return code 0
9: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/pep257.xunit.xml'
 9/11 Test  #9: pep257 ...........................   Passed    0.19 sec
test 10
      Start 10: uncrustify

10: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/uncrustify.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_uncrustify/uncrustify.txt" "--command" "/opt/ros/humble/bin/ament_uncrustify" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/uncrustify.xunit.xml"
10: Test timeout computed to be: 60
10: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
10:  - /opt/ros/humble/bin/ament_uncrustify --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/uncrustify.xunit.xml
10: No code style divergence in file 'include/ros2_benchmark/common.hpp'
10: 
10: No code style divergence in file 'include/ros2_benchmark/data_loader_node.hpp'
10: 
10: No code style divergence in file 'include/ros2_benchmark/monitor_node.hpp'
10: 
10: No code style divergence in file 'include/ros2_benchmark/playback_node.hpp'
10: 
10: No code style divergence in file 'src/data_loader_node.cpp'
10: 
10: No code style divergence in file 'src/monitor_node.cpp'
10: 
10: No code style divergence in file 'src/playback_node.cpp'
10: 
10: No problems found
10: -- run_test.py: return code 0
10: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/uncrustify.xunit.xml'
10/11 Test #10: uncrustify .......................   Passed    0.11 sec
test 11
      Start 11: xmllint

11: Test command: /usr/bin/python3.10 "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/xmllint.xunit.xml" "--package-name" "ros2_benchmark" "--output-file" "/root/ros_ws/build/ros2_benchmark/ament_xmllint/xmllint.txt" "--command" "/opt/ros/humble/bin/ament_xmllint" "--xunit-file" "/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/xmllint.xunit.xml"
11: Test timeout computed to be: 60
11: -- run_test.py: invoking following command in '/root/ros_ws/src/ros2_benchmark/ros2_benchmark':
11:  - /opt/ros/humble/bin/ament_xmllint --xunit-file /root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/xmllint.xunit.xml
11: File 'package.xml' is valid                
11: 
11: No problems found
11: -- run_test.py: return code 0
11: -- run_test.py: verify result file '/root/ros_ws/build/ros2_benchmark/test_results/ros2_benchmark/xmllint.xunit.xml'
11/11 Test #11: xmllint ..........................   Passed    0.72 sec

73% tests passed, 3 tests failed out of 11

Label Time Summary:
copyright      =   0.29 sec*proc (1 test)
cppcheck       =   0.09 sec*proc (1 test)
cpplint        =   0.30 sec*proc (1 test)
flake8         =   0.26 sec*proc (1 test)
launch_test    =  31.74 sec*proc (3 tests)
lint_cmake     =   0.08 sec*proc (1 test)
linter         =   2.05 sec*proc (8 tests)
pep257         =   0.19 sec*proc (1 test)
uncrustify     =   0.11 sec*proc (1 test)
xmllint        =   0.72 sec*proc (1 test)

Total Test time (real) =  33.79 sec

The following tests FAILED:
	  1 - test_data_loader_node_pol.py (Failed)
	  2 - test_monitor_node_pol.py (Timeout)
	  3 - test_playback_node_pol.py (Timeout)
Errors while running CTest
Output from these tests are in: /root/ros_ws/build/ros2_benchmark/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
--- stderr: ros2_benchmark
Errors while running CTest
Output from these tests are in: /root/ros_ws/build/ros2_benchmark/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
---
Finished <<< ros2_benchmark [33.8s]	[ with test failures ]

Summary: 1 package finished [34.0s]
  1 package had stderr output: ros2_benchmark
  1 package had test failures: ros2_benchmark
"""

**Comment by hemalshahNV** [comment]
From the logs, it looks like the script could not open the simple rosbag for testing. Did you happen to install and setup git-lfs correctly? Could you list the file sizes of the contents of `/root/ros_ws/src/ros2_benchmark/ros2_benchmark/test/pol.bag/`? I suspect these are placeholder files and not real files.

**Comment by OsamaThakur** [comment]
In the quick start guide, I do not see git lfs being used. Please let me know What could be missing. As for the content of /pol.bag. The file size is as follows, "metadata.yaml"[1.5KB] | "pol.bag_0.db3"[235MB] | "pol.bag_0.db3.zstd"[86MB]

**Comment by hemalshahNV** [comment]
There is a missing step to install `git-lfs` before you clone (or run `git lfs pull` afterwards) to make sure the POL rosbag is materialized. I'll update that but the file sizes you're reporting looks correct (they'd be a hundred bytes at most otherwise). Have you tried a clean rebuild otherwise? You didn't have git-lfs installed and you had these files downloaded, you say?

**Comment by hemalshahNV** [comment]
Updated the README Quick Start, maybe try running from scratch again to see if that clears up any lingering issues?

**Comment by OsamaThakur** [comment]
It works now :smile: . Thank you so much for the help !
