### ISSUE TITLE
component_container_mt-1 process has died

### ISSUE THREAD

**Issue by bigrobinson** [NVIDIA-ISAAC-ROS/ros2_benchmark#22]
I'm running Isaac ROS nodes in a container on a Jetson with Jetpack 5.1.2 as strongly recommended. I have followed the getting started guide [getting started -- Isaac ROS Benchmark](https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_benchmark/index.html) to a tee. On step 4 of the Quickstart
```
launch_test src/isaac_ros_benchmark/scripts/isaac_ros_apriltag_node.py
```
after running several tests for several minutes, it fails with
```
[ERROR] [component_container_mt-1]: process has died [pid 36669, exit code 1, cmd '/opt/ros/humble/lib/rclcpp_components/component_container_mt --ros-args -r __node:=container -r __ns:=/r2b'].

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
and does not deliver a benchmark summary. I completely tore down the container and image and rebuilt with only the benchmark package and dependencies, according to the guide. The failure was exactly the same. 

What could the problem be?

**Comment by bigrobinson** [comment]
Moved to isaac_ros_benchmark. My bad.

**Comment by NamTruongTran** [comment]
@bigrobinson 

I have the same issue.
What you actually did in order to solve the problem?
Thank you!
